export const provincias = {
    1: {
        codigo: "1",
        nombre: "SAN JOSE",
        cantones: {
            1: {
                codigo: "101",
                nombre: "SAN JOSE",
                distritos: {
                    1: { codigo: "10101", nombre: "CARMEN" },
                    2: { codigo: "10102", nombre: "MERCED" },
                    3: { codigo: "10103", nombre: "HOSPITAL" },
                    4: { codigo: "10104", nombre: "CATEDRAL" },
                    5: { codigo: "10105", nombre: "ZAPOTE" },
                    6: { codigo: "10106", nombre: "SAN FRANCISCO DE DOS RIOS" },
                    7: { codigo: "10107", nombre: "URUCA" },
                    8: { codigo: "10108", nombre: "MATA REDONDA" },
                    9: { codigo: "10109", nombre: "PAVAS" },
                    10: { codigo: "10110", nombre: "HATILLO" },
                    11: { codigo: "10111", nombre: "SAN SEBASTIAN" },
                },
            },
            2: {
                codigo: "102",
                nombre: "ESCAZU",
                distritos: {
                    1: { codigo: "10201", nombre: "ESCAZU" },
                    2: { codigo: "10202", nombre: "SAN ANTONIO" },
                    3: { codigo: "10203", nombre: "SAN RAFAEL" },
                },
            },
            3: {
                codigo: "103",
                nombre: "DESAMPARADOS",
                distritos: {
                    1: { codigo: "10301", nombre: "DESAMPARADOS" },
                    2: { codigo: "10302", nombre: "SAN MIGUEL" },
                    3: { codigo: "10303", nombre: "SAN JUAN DE DIOS" },
                    4: { codigo: "10304", nombre: "SAN RAFAEL ARRIBA" },
                    5: { codigo: "10305", nombre: "SAN ANTONIO" },
                    6: { codigo: "10306", nombre: "FRAILES" },
                    7: { codigo: "10307", nombre: "PATARRA" },
                    8: { codigo: "10308", nombre: "SAN CRISTOBAL" },
                    9: { codigo: "10309", nombre: "ROSARIO" },
                    10: { codigo: "10310", nombre: "DAMAS" },
                    11: { codigo: "10311", nombre: "SAN RAFAEL ABAJO" },
                    12: { codigo: "10312", nombre: "GRAVILIAS" },
                    13: { codigo: "10313", nombre: "LOS GUIDO" },
                },
            },
            4: {
                codigo: "104",
                nombre: "PURISCAL",
                distritos: {
                    1: { codigo: "10401", nombre: "SANTIAGO" },
                    2: { codigo: "10402", nombre: "MERCEDES SUR" },
                    3: { codigo: "10403", nombre: "BARBACOAS" },
                    4: { codigo: "10404", nombre: "GRIFO ALTO" },
                    5: { codigo: "10405", nombre: "SAN RAFAEL" },
                    6: { codigo: "10406", nombre: "CANDELARITA" },
                    7: { codigo: "10407", nombre: "DESAMPARADITOS" },
                    8: { codigo: "10408", nombre: "SAN ANTONIO" },
                    9: { codigo: "10409", nombre: "CHIRES" },
                },
            },
            5: {
                codigo: "105",
                nombre: "TARRAZU",
                distritos: {
                    1: { codigo: "10501", nombre: "SAN MARCOS" },
                    2: { codigo: "10502", nombre: "SAN LORENZO" },
                    3: { codigo: "10503", nombre: "SAN CARLOS" },
                },
            },
            6: {
                codigo: "106",
                nombre: "ASERRI",
                distritos: {
                    1: { codigo: "10601", nombre: "ASERRI" },
                    2: { codigo: "10602", nombre: "TARBACA" },
                    3: { codigo: "10603", nombre: "VUELTA DE JORCO" },
                    4: { codigo: "10604", nombre: "SAN GABRIEL" },
                    5: { codigo: "10605", nombre: "LEGUA" },
                    6: { codigo: "10606", nombre: "MONTERREY" },
                    7: { codigo: "10607", nombre: "SALITRILLOS" },
                },
            },
            7: {
                codigo: "107",
                nombre: "MORA",
                distritos: {
                    1: { codigo: "10701", nombre: "COLON" },
                    2: { codigo: "10702", nombre: "GUAYABO" },
                    3: { codigo: "10703", nombre: "TABARCIA" },
                    4: { codigo: "10704", nombre: "PIEDRAS NEGRAS" },
                    5: { codigo: "10705", nombre: "PICAGRES" },
                    6: { codigo: "10706", nombre: "JARIS" },
                    7: { codigo: "10707", nombre: "QUITIRRISI" },
                },
            },
            8: {
                codigo: "108",
                nombre: "GOICOECHEA",
                distritos: {
                    1: { codigo: "10801", nombre: "GUADALUPE" },
                    2: { codigo: "10802", nombre: "SAN FRANCISCO" },
                    3: { codigo: "10803", nombre: "CALLE BLANCOS" },
                    4: { codigo: "10804", nombre: "MATA DE PLATANO" },
                    5: { codigo: "10805", nombre: "IPIS" },
                    6: { codigo: "10806", nombre: "RANCHO REDONDO" },
                    7: { codigo: "10807", nombre: "PURRAL" },
                },
            },
            9: {
                codigo: "109",
                nombre: "SANTA ANA",
                distritos: {
                    1: { codigo: "10901", nombre: "SANTA ANA" },
                    2: { codigo: "10902", nombre: "SALITRAL" },
                    3: { codigo: "10903", nombre: "POZOS" },
                    4: { codigo: "10904", nombre: "URUCA" },
                    5: { codigo: "10905", nombre: "PIEDADES" },
                    6: { codigo: "10906", nombre: "BRASIL" },
                },
            },
            10: {
                codigo: "110",
                nombre: "ALAJUELITA",
                distritos: {
                    1: { codigo: "11001", nombre: "ALAJUELITA" },
                    2: { codigo: "11002", nombre: "SAN JOSECITO" },
                    3: { codigo: "11003", nombre: "SAN ANTONIO" },
                    4: { codigo: "11004", nombre: "CONCEPCION" },
                    5: { codigo: "11005", nombre: "SAN FELIPE" },
                },
            },
            11: {
                codigo: "111",
                nombre: "VAZQUEZ DE CORONADO",
                distritos: {
                    1: { codigo: "11101", nombre: "SAN ISIDRO" },
                    2: { codigo: "11102", nombre: "SAN RAFAEL" },
                    3: { codigo: "11103", nombre: "DULCE NOMBRE DE JESUS" },
                    4: { codigo: "11104", nombre: "PATALILLO" },
                    5: { codigo: "11105", nombre: "CASCAJAL" },
                },
            },
            12: {
                codigo: "112",
                nombre: "ACOSTA",
                distritos: {
                    1: { codigo: "11201", nombre: "SAN IGNACIO" },
                    2: { codigo: "11202", nombre: "GUAITIL" },
                    3: { codigo: "11203", nombre: "PALMICHAL" },
                    4: { codigo: "11204", nombre: "CANGREJAL" },
                    5: { codigo: "11205", nombre: "SABANILLAS" },
                },
            },
            13: {
                codigo: "113",
                nombre: "TIBAS",
                distritos: {
                    1: { codigo: "11301", nombre: "SAN JUAN" },
                    2: { codigo: "11302", nombre: "CINCO ESQUINAS" },
                    3: { codigo: "11303", nombre: "ANSELMO LLORENTE" },
                    4: { codigo: "11304", nombre: "LEON XIII" },
                    5: { codigo: "11305", nombre: "COLIMA" },
                },
            },
            14: {
                codigo: "114",
                nombre: "MORAVIA",
                distritos: {
                    1: { codigo: "11401", nombre: "SAN VICENTE" },
                    2: { codigo: "11402", nombre: "SAN JERONIMO" },
                    3: { codigo: "11403", nombre: "TRINIDAD" },
                },
            },
            15: {
                codigo: "115",
                nombre: "MONTES DE OCA",
                distritos: {
                    1: { codigo: "11501", nombre: "SAN PEDRO" },
                    2: { codigo: "11502", nombre: "SABANILLA" },
                    3: { codigo: "11503", nombre: "MERCEDES" },
                    4: { codigo: "11504", nombre: "SAN RAFAEL" },
                },
            },
            16: {
                codigo: "116",
                nombre: "TURRUBARES",
                distritos: {
                    1: { codigo: "11601", nombre: "SAN PABLO" },
                    2: { codigo: "11602", nombre: "SAN PEDRO" },
                    3: { codigo: "11603", nombre: "SAN JUAN DE MATA" },
                    4: { codigo: "11604", nombre: "SAN LUIS" },
                    5: { codigo: "11605", nombre: "CARARA" },
                },
            },
            17: {
                codigo: "117",
                nombre: "DOTA",
                distritos: {
                    1: { codigo: "11701", nombre: "SANTA MARIA" },
                    2: { codigo: "11702", nombre: "JARDIN" },
                    3: { codigo: "11703", nombre: "COPEY" },
                },
            },
            18: {
                codigo: "118",
                nombre: "CURRIDABAT",
                distritos: {
                    1: { codigo: "11801", nombre: "CURRIDABAT" },
                    2: { codigo: "11802", nombre: "GRANADILLA" },
                    3: { codigo: "11803", nombre: "SANCHEZ" },
                    4: { codigo: "11804", nombre: "TIRRASES" },
                },
            },
            19: {
                codigo: "119",
                nombre: "PEREZ ZELEDON",
                distritos: {
                    1: { codigo: "11901", nombre: "SAN ISIDRO DE EL GENERAL" },
                    2: { codigo: "11902", nombre: "GENERAL" },
                    3: { codigo: "11903", nombre: "DANIEL FLORES" },
                    4: { codigo: "11904", nombre: "RIVAS" },
                    5: { codigo: "11905", nombre: "SAN PEDRO" },
                    6: { codigo: "11906", nombre: "PLATANARES" },
                    7: { codigo: "11907", nombre: "PEJIBAYE" },
                    8: { codigo: "11908", nombre: "CAJON" },
                    9: { codigo: "11909", nombre: "BARU" },
                    10: { codigo: "11910", nombre: "RIO NUEVO" },
                    11: { codigo: "11911", nombre: "PARAMO" },
                    12: { codigo: "11912", nombre: "LA AMISTAD" },
                },
            },
            20: {
                codigo: "120",
                nombre: "LEON CORTES",
                distritos: {
                    1: { codigo: "12001", nombre: "SAN PABLO" },
                    2: { codigo: "12002", nombre: "SAN ANDRES" },
                    3: { codigo: "12003", nombre: "LLANO BONITO" },
                    4: { codigo: "12004", nombre: "SAN ISIDRO" },
                    5: { codigo: "12005", nombre: "SANTA CRUZ" },
                    6: { codigo: "12006", nombre: "SAN ANTONIO" },
                },
            },
        },
    },
    2: {
        codigo: "2",
        nombre: "ALAJUELA",
        cantones: {
            1: {
                codigo: "201",
                nombre: "ALAJUELA",
                distritos: {
                    1: { codigo: "20101", nombre: "ALAJUELA" },
                    2: { codigo: "20102", nombre: "SAN JOSE" },
                    3: { codigo: "20103", nombre: "CARRIZAL" },
                    4: { codigo: "20104", nombre: "SAN ANTONIO" },
                    5: { codigo: "20105", nombre: "GUACIMA" },
                    6: { codigo: "20106", nombre: "SAN ISIDRO" },
                    7: { codigo: "20107", nombre: "SABANILLA" },
                    8: { codigo: "20108", nombre: "SAN RAFAEL" },
                    9: { codigo: "20109", nombre: "RIO SEGUNDO" },
                    10: { codigo: "20110", nombre: "DESAMPARADOS" },
                    11: { codigo: "20111", nombre: "TURRUCARES" },
                    12: { codigo: "20112", nombre: "TAMBOR" },
                    13: { codigo: "20113", nombre: "LA GARITA" },
                    14: { codigo: "20114", nombre: "SARAPIQUI" },
                },
            },
            2: {
                codigo: "202",
                nombre: "SAN RAMON",
                distritos: {
                    1: { codigo: "20201", nombre: "SAN RAMON" },
                    2: { codigo: "20202", nombre: "SANTIAGO" },
                    3: { codigo: "20203", nombre: "SAN JUAN" },
                    4: { codigo: "20204", nombre: "PIEDADES NORTE" },
                    5: { codigo: "20205", nombre: "PIEDADES SUR" },
                    6: { codigo: "20206", nombre: "SAN RAFAEL" },
                    7: { codigo: "20207", nombre: "SAN ISIDRO" },
                    8: { codigo: "20208", nombre: "ANGELES" },
                    9: { codigo: "20209", nombre: "ALFARO" },
                    10: { codigo: "20210", nombre: "VOLIO" },
                    11: { codigo: "20211", nombre: "CONCEPCION" },
                    12: { codigo: "20212", nombre: "ZAPOTAL" },
                    13: { codigo: "20213", nombre: "PEÑAS BLANCAS" },
                    14: { codigo: "20214", nombre: "SAN LORENZO" },
                },
            },
            3: {
                codigo: "203",
                nombre: "GRECIA",
                distritos: {
                    1: { codigo: "20301", nombre: "GRECIA" },
                    2: { codigo: "20302", nombre: "SAN ISIDRO" },
                    3: { codigo: "20303", nombre: "SAN JOSE" },
                    4: { codigo: "20304", nombre: "SAN ROQUE" },
                    5: { codigo: "20305", nombre: "TACARES" },
                    7: { codigo: "20307", nombre: "PUENTE DE PIEDRA" },
                    8: { codigo: "20308", nombre: "BOLIVAR" },
                },
            },
            4: {
                codigo: "204",
                nombre: "SAN MATEO",
                distritos: {
                    1: { codigo: "20401", nombre: "SAN MATEO" },
                    2: { codigo: "20402", nombre: "DESMONTE" },
                    3: { codigo: "20403", nombre: "JESUS MARIA" },
                    4: { codigo: "20404", nombre: "LABRADOR" },
                },
            },
            5: {
                codigo: "205",
                nombre: "ATENAS",
                distritos: {
                    1: { codigo: "20501", nombre: "ATENAS" },
                    2: { codigo: "20502", nombre: "JESUS" },
                    3: { codigo: "20503", nombre: "MERCEDES" },
                    4: { codigo: "20504", nombre: "SAN ISIDRO" },
                    5: { codigo: "20505", nombre: "CONCEPCION" },
                    6: { codigo: "20506", nombre: "SAN JOSE" },
                    7: { codigo: "20507", nombre: "SANTA EULALIA" },
                    8: { codigo: "20508", nombre: "ESCOBAL" },
                },
            },
            6: {
                codigo: "206",
                nombre: "NARANJO",
                distritos: {
                    1: { codigo: "20601", nombre: "NARANJO" },
                    2: { codigo: "20602", nombre: "SAN MIGUEL" },
                    3: { codigo: "20603", nombre: "SAN JOSE" },
                    4: { codigo: "20604", nombre: "CIRRI SUR" },
                    5: { codigo: "20605", nombre: "SAN JERONIMO" },
                    6: { codigo: "20606", nombre: "SAN JUAN" },
                    7: { codigo: "20607", nombre: "ROSARIO" },
                    8: { codigo: "20608", nombre: "PALMITOS" },
                },
            },
            7: {
                codigo: "207",
                nombre: "PALMARES",
                distritos: {
                    1: { codigo: "20701", nombre: "PALMARES" },
                    2: { codigo: "20702", nombre: "ZARAGOZA" },
                    3: { codigo: "20703", nombre: "BUENOS AIRES" },
                    4: { codigo: "20704", nombre: "SANTIAGO" },
                    5: { codigo: "20705", nombre: "CANDELARIA" },
                    6: { codigo: "20706", nombre: "ESQUIPULAS" },
                    7: { codigo: "20707", nombre: "GRANJA" },
                },
            },
            8: {
                codigo: "208",
                nombre: "POAS",
                distritos: {
                    1: { codigo: "20801", nombre: "SAN PEDRO" },
                    2: { codigo: "20802", nombre: "SAN JUAN" },
                    3: { codigo: "20803", nombre: "SAN RAFAEL" },
                    4: { codigo: "20804", nombre: "CARRILLOS" },
                    5: { codigo: "20805", nombre: "SABANA REDONDA" },
                },
            },
            9: {
                codigo: "209",
                nombre: "OROTINA",
                distritos: {
                    1: { codigo: "20901", nombre: "OROTINA" },
                    2: { codigo: "20902", nombre: "MASTATE" },
                    3: { codigo: "20903", nombre: "HACIENDA VIEJA" },
                    4: { codigo: "20904", nombre: "COYOLAR" },
                    5: { codigo: "20905", nombre: "CEIBA" },
                },
            },
            10: {
                codigo: "210",
                nombre: "SAN CARLOS",
                distritos: {
                    1: { codigo: "21001", nombre: "QUESADA" },
                    2: { codigo: "21002", nombre: "FLORENCIA" },
                    3: { codigo: "21003", nombre: "BUENAVISTA" },
                    4: { codigo: "21004", nombre: "AGUAS ZARCAS" },
                    5: { codigo: "21005", nombre: "VENECIA" },
                    6: { codigo: "21006", nombre: "PITAL" },
                    7: { codigo: "21007", nombre: "FORTUNA" },
                    8: { codigo: "21008", nombre: "TIGRA" },
                    9: { codigo: "21009", nombre: "PALMERA" },
                    10: { codigo: "21010", nombre: "VENADO" },
                    11: { codigo: "21011", nombre: "CUTRIS" },
                    12: { codigo: "21012", nombre: "MONTERREY" },
                    13: { codigo: "21013", nombre: "POCOSOL" },
                },
            },
            11: {
                codigo: "211",
                nombre: "ZARCERO",
                distritos: {
                    1: { codigo: "21101", nombre: "ZARCERO" },
                    2: { codigo: "21102", nombre: "LAGUNA" },
                    3: { codigo: "21103", nombre: "TAPEZCO" },
                    4: { codigo: "21104", nombre: "GUADALUPE" },
                    5: { codigo: "21105", nombre: "PALMIRA" },
                    6: { codigo: "21106", nombre: "ZAPOTE" },
                    7: { codigo: "21107", nombre: "BRISAS" },
                },
            },
            12: {
                codigo: "212",
                nombre: "SARCHI",
                distritos: {
                    1: { codigo: "21201", nombre: "SARCHI NORTE" },
                    2: { codigo: "21202", nombre: "SARCHI SUR" },
                    3: { codigo: "21203", nombre: "TORO AMARILLO" },
                    4: { codigo: "21204", nombre: "SAN PEDRO" },
                    5: { codigo: "21205", nombre: "RODRIGUEZ" },
                },
            },
            13: {
                codigo: "213",
                nombre: "UPALA",
                distritos: {
                    1: { codigo: "21301", nombre: "UPALA" },
                    2: { codigo: "21302", nombre: "AGUAS CLARAS" },
                    3: { codigo: "21303", nombre: "SAN JOSE" },
                    4: { codigo: "21304", nombre: "BIJAGUA" },
                    5: { codigo: "21305", nombre: "DELICIAS" },
                    6: { codigo: "21306", nombre: "DOS RIOS" },
                    7: { codigo: "21307", nombre: "YOLILLAL" },
                    8: { codigo: "21308", nombre: "CANALETE" },
                },
            },
            14: {
                codigo: "214",
                nombre: "LOS CHILES",
                distritos: {
                    1: { codigo: "21401", nombre: "LOS CHILES" },
                    2: { codigo: "21402", nombre: "CAÑO NEGRO" },
                    3: { codigo: "21403", nombre: "EL AMPARO" },
                    4: { codigo: "21404", nombre: "SAN JORGE" },
                },
            },
            15: {
                codigo: "215",
                nombre: "GUATUSO",
                distritos: {
                    1: { codigo: "21501", nombre: "SAN RAFAEL" },
                    2: { codigo: "21502", nombre: "BUENAVISTA" },
                    3: { codigo: "21503", nombre: "COTE" },
                    4: { codigo: "21504", nombre: "KATIRA" },
                },
            },
            16: {
                codigo: "216",
                nombre: "RIO CUARTO",
                distritos: {
                    1: { codigo: "21601", nombre: "RIO CUARTO" },
                    2: { codigo: "21602", nombre: "SANTA RITA" },
                    3: { codigo: "21603", nombre: "SANTA ISABEL" },
                },
            },
        },
    },
    3: {
        codigo: "3",
        nombre: "CARTAGO",
        cantones: {
            1: {
                codigo: "301",
                nombre: "CARTAGO",
                distritos: {
                    1: { codigo: "30101", nombre: "ORIENTAL" },
                    2: { codigo: "30102", nombre: "OCCIDENTAL" },
                    3: { codigo: "30103", nombre: "CARMEN" },
                    4: { codigo: "30104", nombre: "SAN NICOLAS" },
                    5: { codigo: "30105", nombre: "AGUACALIENTE" },
                    6: { codigo: "30106", nombre: "GUADALUPE" },
                    7: { codigo: "30107", nombre: "CORRALILLO" },
                    8: { codigo: "30108", nombre: "TIERRA BLANCA" },
                    9: { codigo: "30109", nombre: "DULCE NOMBRE" },
                    10: { codigo: "30110", nombre: "LLANO GRANDE" },
                    11: { codigo: "30111", nombre: "QUEBRADILLA" },
                },
            },
            2: {
                codigo: "302",
                nombre: "PARAISO",
                distritos: {
                    1: { codigo: "30201", nombre: "PARAISO" },
                    2: { codigo: "30202", nombre: "SANTIAGO" },
                    3: { codigo: "30203", nombre: "OROSI" },
                    4: { codigo: "30204", nombre: "CACHI" },
                    5: { codigo: "30205", nombre: "LLANOS DE SANTA LUCIA" },
                    6: { codigo: "30206", nombre: "BIRRISITO" },
                },
            },
            3: {
                codigo: "303",
                nombre: "LA UNION",
                distritos: {
                    1: { codigo: "30301", nombre: "TRES RIOS" },
                    2: { codigo: "30302", nombre: "SAN DIEGO" },
                    3: { codigo: "30303", nombre: "SAN JUAN" },
                    4: { codigo: "30304", nombre: "SAN RAFAEL" },
                    5: { codigo: "30305", nombre: "CONCEPCION" },
                    6: { codigo: "30306", nombre: "DULCE NOMBRE" },
                    7: { codigo: "30307", nombre: "SAN RAMON" },
                    8: { codigo: "30308", nombre: "RIO AZUL" },
                },
            },
            4: {
                codigo: "304",
                nombre: "JIMENEZ",
                distritos: {
                    1: { codigo: "30401", nombre: "JUAN VIÑAS" },
                    2: { codigo: "30402", nombre: "TUCURRIQUE" },
                    3: { codigo: "30403", nombre: "PEJIBAYE" },
                    4: { codigo: "30404", nombre: "LA VICTORIA" },
                },
            },
            5: {
                codigo: "305",
                nombre: "TURRIALBA",
                distritos: {
                    1: { codigo: "30501", nombre: "TURRIALBA" },
                    2: { codigo: "30502", nombre: "LA SUIZA" },
                    3: { codigo: "30503", nombre: "PERALTA" },
                    4: { codigo: "30504", nombre: "SANTA CRUZ" },
                    5: { codigo: "30505", nombre: "SANTA TERESITA" },
                    6: { codigo: "30506", nombre: "PAVONES" },
                    7: { codigo: "30507", nombre: "TUIS" },
                    8: { codigo: "30508", nombre: "TAYUTIC" },
                    9: { codigo: "30509", nombre: "SANTA ROSA" },
                    10: { codigo: "30510", nombre: "TRES EQUIS" },
                    11: { codigo: "30511", nombre: "LA ISABEL" },
                    12: { codigo: "30512", nombre: "CHIRRIPO" },
                },
            },
            6: {
                codigo: "306",
                nombre: "ALVARADO",
                distritos: {
                    1: { codigo: "30601", nombre: "PACAYAS" },
                    2: { codigo: "30602", nombre: "CERVANTES" },
                    3: { codigo: "30603", nombre: "CAPELLADES" },
                },
            },
            7: {
                codigo: "307",
                nombre: "OREAMUNO",
                distritos: {
                    1: { codigo: "30701", nombre: "SAN RAFAEL" },
                    2: { codigo: "30702", nombre: "COT" },
                    3: { codigo: "30703", nombre: "POTRERO CERRADO" },
                    4: { codigo: "30704", nombre: "CIPRESES" },
                    5: { codigo: "30705", nombre: "SANTA ROSA" },
                },
            },
            8: {
                codigo: "308",
                nombre: "EL GUARCO",
                distritos: {
                    1: { codigo: "30801", nombre: "TEJAR" },
                    2: { codigo: "30802", nombre: "SAN ISIDRO" },
                    3: { codigo: "30803", nombre: "TOBOSI" },
                    4: { codigo: "30804", nombre: "PATIO DE AGUA" },
                },
            },
        },
    },
    4: {
        codigo: "4",
        nombre: "HEREDIA",
        cantones: {
            1: {
                codigo: "401",
                nombre: "HEREDIA",
                distritos: {
                    1: { codigo: "40101", nombre: "HEREDIA" },
                    2: { codigo: "40102", nombre: "MERCEDES" },
                    3: { codigo: "40103", nombre: "SAN FRANCISCO" },
                    4: { codigo: "40104", nombre: "ULLOA" },
                    5: { codigo: "40105", nombre: "VARABLANCA" },
                },
            },
            2: {
                codigo: "402",
                nombre: "BARVA",
                distritos: {
                    1: { codigo: "40201", nombre: "BARVA" },
                    2: { codigo: "40202", nombre: "SAN PEDRO" },
                    3: { codigo: "40203", nombre: "SAN PABLO" },
                    4: { codigo: "40204", nombre: "SAN ROQUE" },
                    5: { codigo: "40205", nombre: "SANTA LUCÍA" },
                    6: { codigo: "40206", nombre: "SAN JOSÉ DE LA MONTAÑA" },
                    7: { codigo: "40207", nombre: "PUENTE SALAS" },
                },
            },
            3: {
                codigo: "403",
                nombre: "SANTO DOMINGO",
                distritos: {
                    1: { codigo: "40301", nombre: "SANTO DOMINGO" },
                    2: { codigo: "40302", nombre: "SAN VICENTE" },
                    3: { codigo: "40303", nombre: "SAN MIGUEL" },
                    4: { codigo: "40304", nombre: "PARACITO" },
                    5: { codigo: "40305", nombre: "SANTO TOMAS" },
                    6: { codigo: "40306", nombre: "SANTA ROSA" },
                    7: { codigo: "40307", nombre: "TURES" },
                    8: { codigo: "40308", nombre: "PARA" },
                },
            },
            4: {
                codigo: "404",
                nombre: "SANTA BARBARA",
                distritos: {
                    1: { codigo: "40401", nombre: "SANTA BARBARA" },
                    2: { codigo: "40402", nombre: "SAN PEDRO" },
                    3: { codigo: "40403", nombre: "SAN JUAN" },
                    4: { codigo: "40404", nombre: "JESÚS" },
                    5: { codigo: "40405", nombre: "SANTO DOMINGO" },
                    6: { codigo: "40406", nombre: "PURABÁ" },
                },
            },
            5: {
                codigo: "405",
                nombre: "SAN RAFAEL",
                distritos: {
                    1: { codigo: "40501", nombre: "SAN RAFAEL" },
                    2: { codigo: "40502", nombre: "SAN JOSECITO" },
                    3: { codigo: "40503", nombre: "SANTIAGO" },
                    4: { codigo: "40504", nombre: "ANGELES" },
                    5: { codigo: "40505", nombre: "CONCEPCIÓN" },
                },
            },
            6: {
                codigo: "406",
                nombre: "SAN ISIDRO",
                distritos: {
                    1: { codigo: "40601", nombre: "SAN ISIDRO" },
                    2: { codigo: "40602", nombre: "SAN JOSÉ" },
                    3: { codigo: "40603", nombre: "CONCEPCIÓN" },
                    4: { codigo: "40604", nombre: "SAN FRANCISCO" },
                },
            },
            7: {
                codigo: "407",
                nombre: "BELEN",
                distritos: {
                    1: { codigo: "40701", nombre: "SAN ANTONIO" },
                    2: { codigo: "40702", nombre: "LA RIBERA" },
                    3: { codigo: "40703", nombre: "ASUNCION" },
                },
            },
            8: {
                codigo: "408",
                nombre: "FLORES",
                distritos: {
                    1: { codigo: "40801", nombre: "SAN JOAQUIN" },
                    2: { codigo: "40802", nombre: "BARRANTES" },
                    3: { codigo: "40803", nombre: "LLORENTE" },
                },
            },
            9: {
                codigo: "409",
                nombre: "SAN PABLO",
                distritos: {
                    1: { codigo: "40901", nombre: "SAN PABLO" },
                    2: { codigo: "40902", nombre: "RINCON DE SABANILLA" },
                },
            },
            10: {
                codigo: "410",
                nombre: "SARAPIQUI",
                distritos: {
                    1: { codigo: "41001", nombre: "PUERTO VIEJO" },
                    2: { codigo: "41002", nombre: "LA VIRGEN" },
                    3: { codigo: "41003", nombre: "HORQUETAS" },
                    4: { codigo: "41004", nombre: "LLANURAS DEL GASPAR" },
                    5: { codigo: "41005", nombre: "CUREÑA" },
                },
            },
        },
    },
    5: {
        codigo: "5",
        nombre: "GUANACASTE",
        cantones: {
            1: {
                codigo: "501",
                nombre: "LIBERIA",
                distritos: {
                    1: { codigo: "50101", nombre: "LIBERIA" },
                    2: { codigo: "50102", nombre: "CAÑAS DULCES" },
                    3: { codigo: "50103", nombre: "MAYORGA" },
                    4: { codigo: "50104", nombre: "NACASCOLO" },
                    5: { codigo: "50105", nombre: "CURUBANDE" },
                },
            },
            2: {
                codigo: "502",
                nombre: "NICOYA",
                distritos: {
                    1: { codigo: "50201", nombre: "NICOYA" },
                    2: { codigo: "50202", nombre: "MANSION" },
                    3: { codigo: "50203", nombre: "SAN ANTONIO" },
                    4: { codigo: "50204", nombre: "QUEBRADA HONDA" },
                    5: { codigo: "50205", nombre: "SAMARA" },
                    6: { codigo: "50206", nombre: "NOSARA" },
                    7: { codigo: "50207", nombre: "BELEN DE NOSARITA" },
                },
            },
            3: {
                codigo: "503",
                nombre: "SANTA CRUZ",
                distritos: {
                    1: { codigo: "50301", nombre: "SANTA CRUZ" },
                    2: { codigo: "50302", nombre: "BOLSON" },
                    3: { codigo: "50303", nombre: "VEINTISIETE DE ABRIL" },
                    4: { codigo: "50304", nombre: "TEMPATE" },
                    5: { codigo: "50305", nombre: "CARTAGENA" },
                    6: { codigo: "50306", nombre: "CUAJINIQUIL" },
                    7: { codigo: "50307", nombre: "DIRIA" },
                    8: { codigo: "50308", nombre: "CABO VELAS" },
                    9: { codigo: "50309", nombre: "TAMARINDO" },
                },
            },
            4: {
                codigo: "504",
                nombre: "BAGACES",
                distritos: {
                    1: { codigo: "50401", nombre: "BAGACES" },
                    2: { codigo: "50402", nombre: "FORTUNA" },
                    3: { codigo: "50403", nombre: "MOGOTE" },
                    4: { codigo: "50404", nombre: "RIO NARANJO" },
                },
            },
            5: {
                codigo: "505",
                nombre: "CARRILLO",
                distritos: {
                    1: { codigo: "50501", nombre: "FILADELFIA" },
                    2: { codigo: "50502", nombre: "PALMIRA" },
                    3: { codigo: "50503", nombre: "SARDINAL" },
                    4: { codigo: "50504", nombre: "BELEN" },
                },
            },
            6: {
                codigo: "506",
                nombre: "CAÑAS",
                distritos: {
                    1: { codigo: "50601", nombre: "CAÑAS" },
                    2: { codigo: "50602", nombre: "PALMIRA" },
                    3: { codigo: "50603", nombre: "SAN MIGUEL" },
                    4: { codigo: "50604", nombre: "BEBEDERO" },
                    5: { codigo: "50605", nombre: "POROZAL" },
                },
            },
            7: {
                codigo: "507",
                nombre: "ABANGARES",
                distritos: {
                    1: { codigo: "50701", nombre: "JUNTAS" },
                    2: { codigo: "50702", nombre: "SIERRA" },
                    3: { codigo: "50703", nombre: "SAN JUAN" },
                    4: { codigo: "50704", nombre: "COLORADO" },
                },
            },
            8: {
                codigo: "508",
                nombre: "TILARAN",
                distritos: {
                    1: { codigo: "50801", nombre: "TILARAN" },
                    2: { codigo: "50802", nombre: "QUEBRADA GRANDE" },
                    3: { codigo: "50803", nombre: "TRONADORA" },
                    4: { codigo: "50804", nombre: "SANTA ROSA" },
                    5: { codigo: "50805", nombre: "LIBANO" },
                    6: { codigo: "50806", nombre: "TIERRAS MORENAS" },
                    7: { codigo: "50807", nombre: "ARENAL" },
                    8: { codigo: "50808", nombre: "CABECERAS" },
                },
            },
            9: {
                codigo: "509",
                nombre: "NANDAYURE",
                distritos: {
                    1: { codigo: "50901", nombre: "CARMONA" },
                    2: { codigo: "50902", nombre: "SANTA RITA" },
                    3: { codigo: "50903", nombre: "ZAPOTAL" },
                    4: { codigo: "50904", nombre: "SAN PABLO" },
                    5: { codigo: "50905", nombre: "PORVENIR" },
                    6: { codigo: "50906", nombre: "BEJUCO" },
                },
            },
            10: {
                codigo: "510",
                nombre: "LA CRUZ",
                distritos: {
                    1: { codigo: "51001", nombre: "LA CRUZ" },
                    2: { codigo: "51002", nombre: "SANTA CECILIA" },
                    3: { codigo: "51003", nombre: "GARITA" },
                    4: { codigo: "51004", nombre: "SANTA ELENA" },
                },
            },
            11: {
                codigo: "511",
                nombre: "HOJANCHA",
                distritos: {
                    1: { codigo: "51101", nombre: "HOJANCHA" },
                    2: { codigo: "51102", nombre: "MONTE ROMO" },
                    3: { codigo: "51103", nombre: "PUERTO CARRILLO" },
                    4: { codigo: "51104", nombre: "HUACAS" },
                    5: { codigo: "51105", nombre: "MATAMBU" },
                },
            },
        },
    },
    6: {
        codigo: "6",
        nombre: "PUNTARENAS",
        cantones: {
            1: {
                codigo: "601",
                nombre: "PUNTARENAS",
                distritos: {
                    1: { codigo: "60101", nombre: "PUNTARENAS" },
                    2: { codigo: "60102", nombre: "PITAHAYA" },
                    3: { codigo: "60103", nombre: "CHOMES" },
                    4: { codigo: "60104", nombre: "LEPANTO" },
                    5: { codigo: "60105", nombre: "PAQUERA" },
                    6: { codigo: "60106", nombre: "MANZANILLO" },
                    7: { codigo: "60107", nombre: "GUACIMAL" },
                    8: { codigo: "60108", nombre: "BARRANCA" },
                    10: { codigo: "60110", nombre: "ISLA DEL COCO" },
                    11: { codigo: "60111", nombre: "COBANO" },
                    12: { codigo: "60112", nombre: "CHACARITA" },
                    13: { codigo: "60113", nombre: "CHIRA" },
                    14: { codigo: "60114", nombre: "ACAPULCO" },
                    15: { codigo: "60115", nombre: "EL ROBLE" },
                    16: { codigo: "60116", nombre: "ARANCIBIA" },
                },
            },
            2: {
                codigo: "602",
                nombre: "ESPARZA",
                distritos: {
                    1: { codigo: "60201", nombre: "ESPIRITU SANTO" },
                    2: { codigo: "60202", nombre: "SAN JUAN GRANDE" },
                    3: { codigo: "60203", nombre: "MACACONA" },
                    4: { codigo: "60204", nombre: "SAN RAFAEL" },
                    5: { codigo: "60205", nombre: "SAN JERONIMO" },
                    6: { codigo: "60206", nombre: "CALDERA" },
                },
            },
            3: {
                codigo: "603",
                nombre: "BUENOS AIRES",
                distritos: {
                    1: { codigo: "60301", nombre: "BUENOS AIRES" },
                    2: { codigo: "60302", nombre: "VOLCAN" },
                    3: { codigo: "60303", nombre: "POTRERO GRANDE" },
                    4: { codigo: "60304", nombre: "BORUCA" },
                    5: { codigo: "60305", nombre: "PILAS" },
                    6: { codigo: "60306", nombre: "COLINAS" },
                    7: { codigo: "60307", nombre: "CHANGUENA" },
                    8: { codigo: "60308", nombre: "BIOLLEY" },
                    9: { codigo: "60309", nombre: "BRUNKA" },
                },
            },
            4: {
                codigo: "604",
                nombre: "MONTES DE ORO",
                distritos: {
                    1: { codigo: "60401", nombre: "MIRAMAR" },
                    2: { codigo: "60402", nombre: "UNION" },
                    3: { codigo: "60403", nombre: "SAN ISIDRO" },
                },
            },
            5: {
                codigo: "605",
                nombre: "OSA",
                distritos: {
                    1: { codigo: "60501", nombre: "PUERTO CORTES" },
                    2: { codigo: "60502", nombre: "PALMAR" },
                    3: { codigo: "60503", nombre: "SIERPE" },
                    4: { codigo: "60504", nombre: "BAHIA BALLENA" },
                    5: { codigo: "60505", nombre: "PIEDRAS BLANCAS" },
                    6: { codigo: "60506", nombre: "BAHIA DRAKE" },
                },
            },
            6: {
                codigo: "606",
                nombre: "AGUIRRE",
                distritos: {
                    1: { codigo: "60601", nombre: "QUEPOS" },
                    2: { codigo: "60602", nombre: "SAVEGRE" },
                    3: { codigo: "60603", nombre: "NARANJITO" },
                },
            },
            7: {
                codigo: "607",
                nombre: "GOLFITO",
                distritos: {
                    1: { codigo: "60701", nombre: "GOLFITO" },
                    3: { codigo: "60703", nombre: "GUAYCARA" },
                    4: { codigo: "60704", nombre: "PAVON" },
                },
            },
            8: {
                codigo: "608",
                nombre: "COTO BRUS",
                distritos: {
                    1: { codigo: "60801", nombre: "SAN VITO" },
                    2: { codigo: "60802", nombre: "SABALITO" },
                    3: { codigo: "60803", nombre: "AGUA BUENA" },
                    4: { codigo: "60804", nombre: "LIMONCITO" },
                    5: { codigo: "60805", nombre: "PITTIER" },
                    6: { codigo: "60806", nombre: "GUTIERREZ BRAUN" },
                },
            },
            9: {
                codigo: "609",
                nombre: "PARRITA",
                distritos: { 1: { codigo: "60901", nombre: "PARRITA" } },
            },
            10: {
                codigo: "610",
                nombre: "CORREDORES",
                distritos: {
                    1: { codigo: "61001", nombre: "CORREDOR" },
                    2: { codigo: "61002", nombre: "LA CUESTA" },
                    3: { codigo: "61003", nombre: "CANOAS" },
                    4: { codigo: "61004", nombre: "LAUREL" },
                },
            },
            11: {
                codigo: "611",
                nombre: "GARABITO",
                distritos: {
                    1: { codigo: "61101", nombre: "JACO" },
                    2: { codigo: "61102", nombre: "TARCOLES" },
                    3: { codigo: "61103", nombre: "LAGUNILLAS" },
                },
            },
            12: {
                codigo: "612",
                nombre: "MONTEVERDE",
                distritos: {
                    1: { codigo: "61201", nombre: "MONTEVERDE" },
                }
            },
            13: {
                codigo: "613",
                nombre: "PUERTO JIMENEZ",
                distritos: {
                    1: { codigo: "61301", nombre: "PUERTO JIMENEZ" },
                }
            }
        },
    },
    7: {
        codigo: "7",
        nombre: "LIMON",
        cantones: {
            1: {
                codigo: "701",
                nombre: "LIMON",
                distritos: {
                    1: { codigo: "70101", nombre: "LIMON" },
                    2: { codigo: "70102", nombre: "VALLE LA ESTRELLA" },
                    3: { codigo: "70103", nombre: "RIO BLANCO" },
                    4: { codigo: "70104", nombre: "MATAMA" },
                },
            },
            2: {
                codigo: "702",
                nombre: "POCOCI",
                distritos: {
                    1: { codigo: "70201", nombre: "GUAPILES" },
                    2: { codigo: "70202", nombre: "JIMENEZ" },
                    3: { codigo: "70203", nombre: "RITA" },
                    4: { codigo: "70204", nombre: "ROXANA" },
                    5: { codigo: "70205", nombre: "CARIARI" },
                    6: { codigo: "70206", nombre: "COLORADO" },
                    7: { codigo: "70207", nombre: "LA COLONIA" },
                },
            },
            3: {
                codigo: "703",
                nombre: "SIQUIRRES",
                distritos: {
                    1: { codigo: "70301", nombre: "SIQUIRRES" },
                    2: { codigo: "70302", nombre: "PACUARITO" },
                    3: { codigo: "70303", nombre: "FLORIDA" },
                    4: { codigo: "70304", nombre: "GERMANIA" },
                    5: { codigo: "70305", nombre: "CAIRO" },
                    6: { codigo: "70306", nombre: "ALEGRIA" },
                    7: { codigo: "70307", nombre: "REVENTAZÓN" },
                },
            },
            4: {
                codigo: "704",
                nombre: "TALAMANCA",
                distritos: {
                    1: { codigo: "70401", nombre: "BRATSI" },
                    2: { codigo: "70402", nombre: "SIXAOLA" },
                    3: { codigo: "70403", nombre: "CAHUITA" },
                    4: { codigo: "70404", nombre: "TELIRE" },
                },
            },
            5: {
                codigo: "705",
                nombre: "MATINA",
                distritos: {
                    1: { codigo: "70501", nombre: "MATINA" },
                    2: { codigo: "70502", nombre: "BATAN" },
                    3: { codigo: "70503", nombre: "CARRANDI" },
                },
            },
            6: {
                codigo: "706",
                nombre: "GUACIMO",
                distritos: {
                    1: { codigo: "70601", nombre: "GUACIMO" },
                    2: { codigo: "70602", nombre: "MERCEDES" },
                    3: { codigo: "70603", nombre: "POCORA" },
                    4: { codigo: "70604", nombre: "RIO JIMENEZ" },
                    5: { codigo: "70605", nombre: "DUACARI" },
                },
            },
        },
    },
}